FI-1005 make menu show on top of navbar
inferno-community/fhir-validator-app pull request #39
Opened 2020-11-06 14:23 UTC by czh-orz

This make is to that the dropdown menu will now show above the navbar instead of being cut off by it. 
The problem came about because the navbar has a z-index of 1030, so the dropdown menu was being cut off. I tried adding a margin between the navbar and the rest of the page, but then the menu just became bigger to fill that space. You can also set the menu height to a certain amount of pixels, but I liked this approach better because it should work for all screen sizes.

2020-11-09 20:17 UTC, okeefm requested changes
Prettier in Travis has a couple of corrections it wants you to make to the format of the method, but otherwise this looks good (tested locally)

2020-11-10 18:13 UTC, radamson commented
You can likely `npm run lint:fix` to fix some/all of the errors.

2020-11-12 19:02 UTC, radamson commented
This works, but I tested locally and was able to achieve the same thing by adjusting the footer z-index instead.

i.e.

https://github.com/inferno-community/fhir-validator-app/blob/0609f2a889af9f413b73737d4a9b9cad17d288a3/src/components/App.tsx#L37

becomes:

`<nav className="navbar fixed-bottom navbar-light bg-light" style={{zIndex: "auto"}}>`

2020-11-18 14:44 UTC, okeefm approved these changes
Works for me. Looks good!

2020-11-18 14:45 UTC, merged